const books = [
  {
    id: 1,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'Demo Book 1',
    price: 100,
  },
  {
    id: 2,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'Demo Book 1',
    price: 20,
  },
  {
    id: 3,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'Demo Book 1',
    price: 200,
  },
  {
    id: 4,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 50,
  },
  {
    id: 5,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 6,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 7,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 8,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 20,
  },
  {
    id: 9,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 200,
  },
  {
    id: 10,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 50,
  },
  {
    id: 11,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 12,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 13,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 14,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 20,
  },
  {
    id: 15,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 200,
  },
  {
    id: 16,
    discount: 40,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 50,
  },
  {
    id: 17,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
  {
    id: 18,
    discount: 50,
    cover: './images/SlideCard/slide-1.png',
    name: 'BCS Book',
    price: 100,
  },
];
export default books;
